name: build
on: [push]
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup node env
        uses: actions/setup-node@v2
        with: 
          node-version: 18
      - name: install deps
        run: yarn install
      - name: build project
        run: yarn build

  